### ISSUE TITLE
How can I simulate the fluctuation of bandwidth?

### ISSUE THREAD

**Issue by JohnPekl** [djvergad/dash#16]
Hi, thank for your simulation.

Have you ever implemented the fluctuation of bandwidth in the code?
In the NS3 forum, they addressed us how to simulate the bandwidth fluctuation by changing bandwidth of the link.
https://groups.google.com/forum/#!msg/ns-3-users/rJaWMVixcmY/z1dy8gRsAwAJ

**Comment by djvergad** [comment]
@sotoremydocuments Thanks, I will check it out. In the meantime, do you have an example file using dash with fluctuating bandwidth? If you create a pull request I can merge it into the repository.

**Comment by djvergad** [comment]
Bandwidth fluctuation example is found at https://github.com/djvergad/dash/blob/master/examples/link-example.cc
