### ISSUE TITLE
installation error

### ISSUE THREAD

**Issue by AlbertTHuanG** [djvergad/dash#17]
Hey,i get a error about installation.
after installing ns3 and configuring,I run the instruction
./waf --run 'src/dash/examples/dash-example --users=3 --protocol="ns::FdashClient" --LinkRate=1000Kbps'
and get a error:
Waf: Entering directory `/home/albert/repos/ns-3-allinone/ns-3-dev/build'
[1786/2466] Compiling src/dash/model/algorithms/osmp-client.cc
[1791/2466] Compiling src/dash/model/dash-server.cc
../src/dash/model/dash-server.cc: In static member function ‘static ns3::TypeId ns3::DashServer::GetTypeId()’:
../src/dash/model/dash-server.cc:58:60: error: ‘ns3::TypeId ns3::TypeId::AddTraceSource(std::__cxx11::string, std::__cxx11::string, ns3::Ptr<const ns3::TraceSourceAccessor>)’ is deprecated [-Werror=deprecated-declarations]
             MakeTraceSourceAccessor(&DashServer::m_rxTrace));
                                                            ^
In file included from ./ns3/object-base.h:23:0,
                 from ./ns3/object.h:29,
                 from ./ns3/node.h:26,
                 from ../src/dash/model/dash-server.cc:26:
./ns3/type-id.h:439:10: note: declared here
   TypeId AddTraceSource (std::string name,
          ^
cc1plus: all warnings being treated as errors

Waf: Leaving directory `/home/albert/repos/ns-3-allinone/ns-3-dev/build'
Build failed
 -> task in 'ns3-dash' failed with exit status 1 (run with -v to display more information)
how can i solve this problem?(using ubuntu16.04 ns3.29

**Comment by djvergad** [comment]
Thanks for reporting.

Issue has been fixed by commit bb2aadba3315fbf1489f062f6d64402a122f2b41, after you pull it should compile properly.
