### ISSUE TITLE
DASH Extension for multiple streams

### ISSUE THREAD

**Issue by SASR75** [djvergad/dash#19]
If we have multiple streams at the server-side can we add multiple players (each player requesting a single stream over the same channel from the server)  at the client-side? Will that is equivalent to a separate dash client for each of the stream requesting the segments over a channel for different streams same as in the multi-client scenario. Thanks

**Comment by djvergad** [comment]
Currently the `DashClient` class contains a single `MpegPlayer` object, but you may add multiple `DashClient` apps to the same node in the network.

`DashClient` you be extended theoretically to support multiple `MpegPlayer` instances, now sure what the point would be though...

**Comment by SASR75** [comment]
What I want is to create multiple video streaming at the same client node. What could be the possible approach 1) Running multiple applications on the same client node, for each application the same client requests different stream from the server, or 2) Extending the single player on the client-side such that each player requests a different stream from the server with a single application on the client-side.
Thanks

**Comment by djvergad** [comment]
Yes for this the best approach is to install multiple "DashClient" applications on the same node.

**Comment by SASR75** [comment]
Thanks
